--
-- PostgreSQL database dump
--

-- Dumped from database version 14.7
-- Dumped by pg_dump version 14.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activite (
    id bigint NOT NULL,
    description character varying(255),
    duree character varying(255),
    lieu character varying(255),
    nom_activity character varying(255),
    prix double precision NOT NULL,
    image_url character varying(255)
);


ALTER TABLE public.activite OWNER TO postgres;

--
-- Name: activite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.activite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contact (
    id integer NOT NULL,
    email character varying(255),
    message text,
    nom character varying(255),
    prenom character varying(255)
);


ALTER TABLE public.contact OWNER TO postgres;

--
-- Name: contact_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hebergement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hebergement (
    id bigint NOT NULL,
    adresse character varying(255),
    capacite integer NOT NULL,
    description character varying(255),
    etoiles integer NOT NULL,
    image_url character varying(255),
    nom_hibergement character varying(255),
    prix_par_nuit double precision NOT NULL,
    type character varying(255),
    lieu character varying(255)
);


ALTER TABLE public.hebergement OWNER TO postgres;

--
-- Name: hebergement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hebergement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hebergement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pack; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pack (
    id bigint NOT NULL,
    description character varying(255),
    destination character varying(255),
    duree integer NOT NULL,
    id_activite bigint,
    id_hebergement bigint,
    id_restaurant bigint,
    id_transport bigint,
    image_url character varying(1000),
    nom_pack character varying(255),
    prix_total double precision NOT NULL,
    planning text
);


ALTER TABLE public.pack OWNER TO postgres;

--
-- Name: pack_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pack ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pack_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservation (
    id_reservation bigint NOT NULL,
    date_debut date,
    date_fin date,
    date_reservation timestamp(6) without time zone,
    destination character varying(255),
    id_pack bigint,
    id_user integer,
    mode_paiement character varying(255),
    montant_total double precision,
    nb_personnes integer,
    pack_titre character varying(255),
    statut character varying(255),
    statut_paiement character varying(255)
);


ALTER TABLE public.reservation OWNER TO postgres;

--
-- Name: reservation_id_reservation_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservation ALTER COLUMN id_reservation ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_reservation_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restauration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restauration (
    id bigint NOT NULL,
    description character varying(255),
    imageurl character varying(255),
    nom_restauration character varying(255),
    prix double precision NOT NULL,
    repas_inclus character varying(255),
    type_cuisine character varying(255),
    lieu character varying(255)
);


ALTER TABLE public.restauration OWNER TO postgres;

--
-- Name: restauration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restauration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restauration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transport; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transport (
    id bigint NOT NULL,
    date_depart character varying(255),
    description character varying(255),
    heure character varying(255),
    prix double precision NOT NULL,
    type_transport character varying(255),
    ville_arrivee character varying(255),
    ville_depart character varying(255)
);


ALTER TABLE public.transport OWNER TO postgres;

--
-- Name: transport_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.utilisateur (
    id integer NOT NULL,
    email character varying(255),
    mot_de_passe character varying(255),
    nom character varying(255),
    role character varying(255),
    prenom character varying(255),
    telephone character varying(255),
    ville character varying(255)
);


ALTER TABLE public.utilisateur OWNER TO postgres;

--
-- Name: utilisateur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.utilisateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilisateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: activite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.activite (id, description, duree, lieu, nom_activity, prix, image_url) FROM stdin;
3	Aventure en quad le long des plages et dunes d’Essaouira.	2 heures	Essaouira	Balade en quad sur la plage	180	http://localhost:5006/uploads/images/1776603964954_OIP (7).webp
4	Découverte des studios Atlas et des décors de films célèbres.	2 heures	Ouarzazate	Visite des studios de cinéma	120	http://localhost:5006/uploads/images/1776604051980_cineam.jpg
1	Expérience dans le déser	2 heures	Marrakech	Balade en chameau	150	http://localhost:5006/uploads/images/1776603574340_OIP (6).webp
\.


--
-- Data for Name: contact; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contact (id, email, message, nom, prenom) FROM stdin;
1	alami@gmail.com	parfait	alami	ahmed
\.


--
-- Data for Name: hebergement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.hebergement (id, adresse, capacite, description, etoiles, image_url, nom_hibergement, prix_par_nuit, type, lieu) FROM stdin;
4	Marrakech Medina	2	hotel marhba	4	http://localhost:5006/uploads/images/1776118771232_Riad-FullScreen.jpg	Riad Atlas	1000	Hotel	Marrakech
\.


--
-- Data for Name: pack; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pack (id, description, destination, duree, id_activite, id_hebergement, id_restaurant, id_transport, image_url, nom_pack, prix_total, planning) FROM stdin;
14	Découvrez la ville ocre, ses souks et ses jardins secrets.	Marrakech	3	1	4	5	\N	http://localhost:5006/uploads/images/1776638951748_OIP (9).webp	Escapade à Marrakech	3270	[{"day":1,"title":"Jour 1","matin":"vol ou transfert jusqu'à l'hôtel, installation.","apresMidi":"Déjeuner libre puis visite du Jardin Majorelle et du quartier de la Guéliz.","soir":"Dîner sur une terrasse de la place Jemaa el-Fna, spectacle de charmeurs de serpents."},{"day":2,"title":"Jour 2","matin":"Visite de la Médersa Ben Youssef et du Musée de Marrakech.","apresMidi":"Souk Semmarine, atelier de poterie, puis Palais de la Bahia.","soir":"Dîner traditionnel dans un riad avec musique gnawa."},{"day":3,"title":"Jour 3","matin":"Départ matinal pour le désert d'Agafay (40 min). Balade à dos de dromadaire.","apresMidi":"Déjeuner bivouac, randonnée quad ou VTT, pause thé à la tente.","soir":"Dîner sous les étoiles, feu de camp et nuit en campement (option retour possible)."}]
\.


--
-- Data for Name: reservation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reservation (id_reservation, date_debut, date_fin, date_reservation, destination, id_pack, id_user, mode_paiement, montant_total, nb_personnes, pack_titre, statut, statut_paiement) FROM stdin;
1	2026-04-21	2026-04-23	2026-04-20 00:02:19.442513	Marrakech	14	8	Carte bancaire	3270	1	Escapade à Marrakech	En attente	En attente
\.


--
-- Data for Name: restauration; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restauration (id, description, imageurl, nom_restauration, prix, repas_inclus, type_cuisine, lieu) FROM stdin;
5	Cuisine traditionnelle	http://localhost:5006/uploads/images/1776119089280_OIP (4).webp	Le jardin	120	Petit-déjeuner	Marocaine	Marrakech
\.


--
-- Data for Name: transport; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transport (id, date_depart, description, heure, prix, type_transport, ville_arrivee, ville_depart) FROM stdin;
1	2026-05-01	Train ONCF	08:00	150	Train	Marrakech	Casablanca
\.


--
-- Data for Name: utilisateur; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.utilisateur (id, email, mot_de_passe, nom, role, prenom, telephone, ville) FROM stdin;
1	admin@gmail.com	admin123	admin	ADMIN	principale	0760942691	rabat
2	alami@gmail.com	123456789	alami	ROLE_USER	ahmed	+212652628642	Kénitra
4	alami123@gmail.com	$2a$10$BqvXMGGadpE1W1vYsk1yQe2.AMhwL4aW9bCQvms0MqkjozUJOyfye	alami	ROLE_USER	ahmed	+212652628642	\N
3	ouinkhermaroua@gmail.com	$2a$10$I4SOnpe1oLfKBrJboxyR6uOJd8mcjvfRlRn6dzxxvAYPkBwI19irC	maroua	ROLE_USER	ouinkher1	+212652628642	Casablanca
6	admin@smartmorocco.com	$2a$10$7EqJtq98hPqEX7fNZaFWoOhi5gH1x1o1t4bm/FYnGV8eK3opgDd4a	Admin	admin	System	0600000000	\N
7	admin1@gmail.com	$2a$10$6dlZ/RimdC43SSTSFWOt5.2DoyOW86boHxq2jMDs6K8lELAPovM3u	admin	admin	principale	+212652628642	\N
8	marouaouinkher@gmail.com	$2a$10$ZzEFWlTqNgOXZn23RLlWtemT1A5niiwMbXy/b1trJ4c2fOIF6uWRq	maroua	ROLE_USER	maroua	0625316987	\N
\.


--
-- Name: activite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activite_id_seq', 6, true);


--
-- Name: contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contact_id_seq', 1, true);


--
-- Name: hebergement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hebergement_id_seq', 5, true);


--
-- Name: pack_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pack_id_seq', 14, true);


--
-- Name: reservation_id_reservation_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservation_id_reservation_seq', 1, true);


--
-- Name: restauration_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restauration_id_seq', 5, true);


--
-- Name: transport_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transport_id_seq', 1, true);


--
-- Name: utilisateur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.utilisateur_id_seq', 8, true);


--
-- Name: activite activite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activite
    ADD CONSTRAINT activite_pkey PRIMARY KEY (id);


--
-- Name: contact contact_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact
    ADD CONSTRAINT contact_pkey PRIMARY KEY (id);


--
-- Name: hebergement hebergement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hebergement
    ADD CONSTRAINT hebergement_pkey PRIMARY KEY (id);


--
-- Name: pack pack_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pack
    ADD CONSTRAINT pack_pkey PRIMARY KEY (id);


--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (id_reservation);


--
-- Name: restauration restauration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restauration
    ADD CONSTRAINT restauration_pkey PRIMARY KEY (id);


--
-- Name: transport transport_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transport
    ADD CONSTRAINT transport_pkey PRIMARY KEY (id);


--
-- Name: utilisateur ukrma38wvnqfaf66vvmi57c71lo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur
    ADD CONSTRAINT ukrma38wvnqfaf66vvmi57c71lo UNIQUE (email);


--
-- Name: utilisateur utilisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur
    ADD CONSTRAINT utilisateur_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

