spring.application.name=smart_morocco
server.port=5006
# Connexion à PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Tourisme
spring.datasource.username=postgres
spring.datasource.password=123456789

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
